# add group
#- name: Ensure group "ES_GROUP" exists
#  group:
#    name: "{{ ES_GROUP }}"
#    state: present

# add user
#- name: Added user
#  user:
#    name: "{{ ES_OWNER }}"
#    groups: "{{ ES_GROUP }}"

# unpack and make link
#- include: download_unpack.yml

#include os parameter setting.
#- include: os_setting.yml

# make directory and apply application setting
- include: es_setting.yml

# stop es
- include: ../../es_startstop/tasks/es_shutdown.yml
  ignore_errors: True

# start elasticsearch
- include: ../../es_startstop/tasks/es_start.yml