---
# os setting
- name: setting for vm.overcommit_memory in sysctl.conf
  sysctl: name=vm.max_map_count value=262144 sysctl_set=yes state=present reload=yes
  ignore_errors: yes

- name: setting for vm.swappiness in sysctl.conf
  sysctl: name=vm.swappiness value=0 sysctl_set=yes state=present reload=yes
  ignore_errors: yes

- name: deleting nproc ulimit setting
  lineinfile: dest=/etc/security/limits.d/90-nproc.conf  regexp="^\*" state=absent
#todo remove setting when second install time.
- name: setting ulimit
  lineinfile: dest=/etc/security/limits.conf  state=present insertbefore="^# End of file" line="*                soft    nofile          65536\n*                hard    nofile          65536"
