# add group
- name: Ensure group "ES_GROUP" exists
  group:
    name: "{{ KIBANA_GROUP }}"
    state: present

# add user
- name: Added user
  user:
    name: "{{ KIBANA_OWNER }}"
    groups: "{{ KIBANA_GROUP }}"

# unpack and make link
- include: download_unpack.yml

# make directory and apply application setting
- include: kibana_setting.yml

# stop kibana
- include: ../../kibana_startstop/tasks/kibana_shutdown.yml
  ignore_errors: True

# start kibana
- include: ../../kibana_startstop/tasks/kibana_start.yml
