- name: start elasticsearch
  shell: "`nohup {{ ES_HOME_DIR }}_{{ item.node }}/bin/startup.sh`"
  become_user: "{{ ES_OWNER }}"
  with_items:
    - "{{ ES_SERVER_NODES_INFO }}"

- wait_for:
    host: "{{ IPV4_ADDR }}"
    port: "{{ item.port }}"
    delay: 2
  with_items:
    - "{{ ES_SERVER_NODES_INFO }}"